# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1230a21c9109f62b681d9fca14d420adf496c6ac1d30a3569cb58010f5da3b68b8a9c86ec769f243568beec6699de26c122b1e7886ba4f0ae298413fe116d08

test:
  secret_key_base: c156d0634838b29634447a82550b84b3bca4e152da35e93ea18f684e59c3a2ee23afdc9ca5f6928f1b1d59b98e1a2f04c7e67da11acbfe5574a714ddd671b6e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
